### ISSUE TITLE
Feature Request: Custom drive names

### ISSUE THREAD

**Issue by serkonda7** [sungaila/SUBSTitute#16]
[Visual subst](https://www.ntwind.com/software/visual-subst.html) has a way to name the drives with custom names.

Maybe it is possible to add this feature for substitute as well?

**Comment by sungaila** [comment]
Hi @serkonda7, good idea. I'll take a look at it.

**Comment by serkonda7** [comment]
Edit: Oops, I meant Visual subst. Sorry, windows is not really my field of expertise

**Comment by sungaila** [comment]
So I've been searching the internet for labling virtual drives created with `subst`. Turns out there is no official way to do this.

There is a hacky workaround where the original drive is renamed, just before calling `subst`, and then renaming it back. This involves writing to the registry. But this workaround won't survive a reboot.

Then there is the option to use network drives (`net use`) instead but it has it's own drawbacks like having to deal with the network loopback.

Until I find a permanent solution, I won't try to hack this.

**Comment by serkonda7** [comment]
Alright, thank you very much for looking into this!
